language: minimal

services:
  - docker

sudo: required

before_install:
  - docker pull dcurylo/fsharp-mono-netcore:2.1.503
  - chmod 755 ./*.sh

jobs:
  include:
    - stage: "CI"
      script: docker run -v "${PWD}:/var/fantomas" -w "/var/fantomas" dcurylo/fsharp-mono-netcore:2.1.503  bash -c "./build.sh"
    - stage: "TestExternalProjects"
      script: docker run -v "${PWD}:/var/fantomas" -w "/var/fantomas" dcurylo/fsharp-mono-netcore:2.1.503  bash -c "./build.sh -t TestExternalProjects" 
      if: branch = test-external-projects
    - stage: "trigger fantomas-ui pipeline"
      script: 
        - "curl -X POST -F token=$TOKEN -F ref=preview https://gitlab.com/api/v4/projects/8920076/trigger/pipeline"
      if: branch = nuget
